name: Bug Report
description: Report a bug or issue with kr_ui
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Import kr_ui package
        2. Create a GlassyCard with...
        3. Run the app
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      placeholder: |
        ```dart
        import 'package:kr_ui/kr_ui.dart';
        
        // Your code here
        ```
      render: dart
    validations:
      required: false

  - type: input
    id: flutter-version
    attributes:
      label: Flutter Version
      description: "Run `flutter --version` in your terminal"
      placeholder: "e.g., Flutter 3.27.0 • Dart 3.6.0"
    validations:
      required: true

  - type: input
    id: kr-ui-version
    attributes:
      label: kr_ui Version
      description: "Check your pubspec.yaml"
      placeholder: "e.g., 0.0.1"
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Affected Platforms
      description: Which platforms are affected?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images or videos here

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant error logs or stack traces
      placeholder: |
        ```
        Paste logs here
        ```
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
