name: Feature Request
description: Suggest a new feature or enhancement for kr_ui
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your ideas to make kr_ui better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What are you trying to accomplish?
      placeholder: "I'm frustrated when... / It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API/Usage
      description: How would you like to use this feature in code?
      placeholder: |
        ```dart
        // Example of how the API could work
        GlassyCard(
          newProperty: value,
          // ...
        )
        ```
      render: dart
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: What other approaches did you think about?
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. In my app, I need to...
        2. When building a dashboard, it would help to...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/Blocking
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples from Other Libraries
      description: Are there examples of this feature in other UI libraries or frameworks?
      placeholder: "Package X does this by... / Similar to Material 3's..."

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Design References
      description: If applicable, add mockups, designs, or visual references
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I am willing to help implement this feature (if possible)
          required: false
